camera_matrix:
  rows: 3
  cols: 3
  data: [554.3827126, 0.0, 320.5, 0.0, 554.3827126, 240.5, 0.0, 0.0, 1.0]

distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.0, 0.0, 0.0, 0.0, 0.0]

distortion_model: plumb_bob
image_width: 640
image_height: 480
