image_width: 640
image_height: 480
camera_name: sony_cam2
camera_matrix:
  rows: 3
  cols: 3
  data: [11683.62060276201, 0, 463.106401998351, 0, 15454.65242011858, 218.4192915882346, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [6.276740343951348, -3076.679776198238, -0.03425455535963665, 0.05884685533288941, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [11647.34765625, 0, 463.7940054360952, 0, 0, 15480.296875, 217.5043037571886, 0, 0, 0, 1, 0]