image_width: 1080
image_height: 720
camera_name: sony_cam1
camera_matrix:
  rows: 3
  cols: 3
  data: [5263.046294182664, 0, 517.3373225171953, 0, 6226.921407797355, 498.2350269811809, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.2009685410365935, -37.21749724731664, 0.04194812149595746, -0.02332828149289618, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [5228.94384765625, 0, 512.163734036847, 0, 0, 6189.39111328125, 501.5953262370531, 0, 0, 0, 1, 0]