image_width: 640
image_height: 480
camera_name: sony_cam3
camera_matrix:
  rows: 3
  cols: 3
  data: [20125.27329469171, 0, 317.317890260488, 0, 24653.01600554101, 239.9398847585528, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [1.121043378950134, -0.02642150431494738, 0.002277359505949104, 0.01200219562951199, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [20102.720703125, 0, 317.0290687576453, 0, 0, 24620.798828125, 239.4702822013114, 0, 0, 0, 1, 0]