image_width: 640
image_height: 480
camera_name: sony_cam2
camera_matrix:
  rows: 3
  cols: 3
  data: [11109.90310919776, 0, 318.5527010196486, 0, 16163.43367097328, 238.1599445409366, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [12.64018437092663, -13908.06786189797, -0.1600773374872461, -0.06536356901396315, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [11125.04296875, 0, 316.0910751955307, 0, 0, 16236.6005859375, 234.9922685835718, 0, 0, 0, 1, 0]