image_width: 640
image_height: 480
camera_name: sony_cam2
camera_matrix:
  rows: 3
  cols: 3
  data: [15893.27441568437, 0, 381.5108237918799, 0, 20710.97441498411, 304.2889947830108, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [1.845762941081436, 11.02088908783874, 0.006734962066303428, 0.03595399175577645, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [15873.970703125, 0, 381.5748418952971, 0, 0, 20705.62109375, 303.7140597591751, 0, 0, 0, 1, 0]