image_width: 640
image_height: 480
camera_name: sony_cam3
camera_matrix:
  rows: 3
  cols: 3
  data: [12994.72689733887, 0, 327.3886952937422, 0, 15096.78455673414, 237.8607454872752, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [3.297509440765291, 0.3085368093381975, -0.007350333753878235, 0.117407590018012, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [13007.2822265625, 0, 329.9405997099893, 0, 0, 15189.7158203125, 237.2241994164606, 0, 0, 0, 1, 0]