image_width: 640
image_height: 480
camera_name: sony_cam1
camera_matrix:
  rows: 3
  cols: 3
  data: [18103.6885096617, 0, 312.3551030696615, 0, 22761.81696774374, 245.1596636486257, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [6.477347137317384, 7.210074693495859, 0.1475156470105229, -0.2244654791415547, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [18162.298828125, 0, 307.7404442025545, 0, 0, 22939.451171875, 246.6932383829208, 0, 0, 0, 1, 0]