image_width: 640
image_height: 480
camera_name: sony_cam2
camera_matrix:
  rows: 3
  cols: 3
  data: [12557.01489345393, 0, 329.2282478137051, 0, 13189.36265021592, 242.0976953410148, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [6.644635779482821, -5238.462084864445, 0.00648034594805666, 0.1126173113240208, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [12563.1982421875, 0, 331.6571760212628, 0, 0, 13256.2275390625, 241.7322208295082, 0, 0, 0, 1, 0]