image_width: 640
image_height: 480
camera_name: sony_cam1
camera_matrix:
  rows: 3
  cols: 3
  data: [13995.32033979942, 0, 330.539504469455, 0, 14581.56154128204, 239.0521067200622, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.01912879130004318, 1.308605625713202, 0.03908693528410017, 0.1002539209513875, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [13985.2451171875, 0, 332.5565394689638, 0, 0, 14615.4228515625, 239.2847218612296, 0, 0, 0, 1, 0]